spring.application.name=authentication-service

server.port=8082

spring.datasource.url=jdbc:postgresql://database-1.czecaqmg888k.us-east-1.rds.amazonaws.com:5432/authentication_db
spring.datasource.username=postgres
spring.datasource.password=${RDS_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics

security.jwt.secret=${JWT_SECRET:c2lkbmV5LWJhbmtpbmctcGxhdGZvcm0tand0LXNlY3JldC0yMDI2}
security.jwt.expiration-seconds=3600