spring.application.name=ledger-service

server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5436/ledger
spring.datasource.username=ledger_user
spring.datasource.password=ledger_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
security.jwt.secret=${JWT_SECRET:c2lkbmV5LWJhbmtpbmctcGxhdGZvcm0tand0LXNlY3JldC0yMDI2}

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=ledger-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sidney.banking.ledger.event
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.sidney.banking.ledger.event.AccountCreatedEvent

# Kafka topics
topics.account-created=account-created

# Outbox
outbox.publisher.delay-ms=5000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always