spring.application.name=account-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/account_db
spring.datasource.username=banking
spring.datasource.password=banking
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

security.jwt.secret=${JWT_SECRET:c21kbmV5LWJhbmtpbmctcGxhdGZvcm0tand0LXNlY3JldC0yMDI2}
