spring.application.name=account-service

server.port=8084

# =========================
# PostgreSQL / Amazon RDS
# =========================
spring.datasource.url=jdbc:postgresql://database-1.czecaqmg888k.us-east-1.rds.amazonaws.com:5432/account_db
spring.datasource.username=postgres
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =========================
# Actuator / Monitoramento
# =========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =========================
# JWT
# =========================
security.jwt.secret=${JWT_SECRET:c2lkbmV5LWJhbmtpbmctcGxhdGZvcm0tand0LXNlY3JldC0yMDI2}

# =========================
# Kafka / Amazon MSK Serverless
# =========================
spring.kafka.bootstrap-servers=boot-sfn1grdl.c1.kafka-serverless.us-east-1.amazonaws.com:9098

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=AWS_MSK_IAM
spring.kafka.properties.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
spring.kafka.properties.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# =========================
# Kafka Topics
# =========================
topics.account-created=banking.account.events

# =========================
# Outbox
# =========================
outbox.publisher.fixed-delay=5000

# =========================
# Redis
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis_password